[2021-11-24 19:21:03,542: INFO: 01_base_model_creation]: 
********************
[2021-11-24 19:21:03,542: INFO: 01_base_model_creation]: >>>>> stage creating base model started <<<<<
[2021-11-24 19:21:03,542: ERROR: 01_base_model_creation]: 'Namespace' object has no attribute 'params'
Traceback (most recent call last):
  File "src/01_base_model_creation.py", line 66, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
AttributeError: 'Namespace' object has no attribute 'params'
[2021-11-24 19:22:11,486: INFO: 01_base_model_creation]: 
********************
[2021-11-24 19:22:11,487: INFO: 01_base_model_creation]: >>>>> stage creating base model started <<<<<
[2021-11-24 19:22:11,487: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2021-11-24 19:22:11,804: ERROR: 01_base_model_creation]: module 'keras.api._v2.keras' has no attribute 'model'
Traceback (most recent call last):
  File "src/01_base_model_creation.py", line 66, in <module>
    main(config_path=parsed_args.config)
  File "src/01_base_model_creation.py", line 49, in main
    model =  tf.keras.model.Sequential(LAYERS)
AttributeError: module 'keras.api._v2.keras' has no attribute 'model'
[2021-11-24 19:22:33,045: INFO: 01_base_model_creation]: 
********************
[2021-11-24 19:22:33,045: INFO: 01_base_model_creation]: >>>>> stage creating base model started <<<<<
[2021-11-24 19:22:33,046: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2021-11-24 19:22:34,464: ERROR: 01_base_model_creation]: module 'keras.api._v2.keras' has no attribute 'optimizer'
Traceback (most recent call last):
  File "src/01_base_model_creation.py", line 66, in <module>
    main(config_path=parsed_args.config)
  File "src/01_base_model_creation.py", line 52, in main
    OPTIMIZER = tf.keras.optimizer.SGD(learning_rate = 1e-3)
AttributeError: module 'keras.api._v2.keras' has no attribute 'optimizer'
[2021-11-24 19:22:56,373: INFO: 01_base_model_creation]: 
********************
[2021-11-24 19:22:56,373: INFO: 01_base_model_creation]: >>>>> stage creating base model started <<<<<
[2021-11-24 19:22:56,374: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2021-11-24 19:22:57,252: ERROR: 01_base_model_creation]: Invalid keyword argument(s) in `compile()`: ({'metric'},). Valid keyword arguments include "cloning", "experimental_run_tf_function", "distribute", "target_tensors", or "sample_weight_mode".
Traceback (most recent call last):
  File "src/01_base_model_creation.py", line 66, in <module>
    main(config_path=parsed_args.config)
  File "src/01_base_model_creation.py", line 54, in main
    model.compile(loss=LOSS, optimizer=OPTIMIZER, metric=METRICS)
  File "D:\DLCVNLP\New folder\Transfer_Learning_DLCVNLP\env\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "D:\DLCVNLP\New folder\Transfer_Learning_DLCVNLP\env\lib\site-packages\keras\engine\training.py", line 2786, in _validate_compile
    raise TypeError('Invalid keyword argument(s) in `compile()`: '
TypeError: Invalid keyword argument(s) in `compile()`: ({'metric'},). Valid keyword arguments include "cloning", "experimental_run_tf_function", "distribute", "target_tensors", or "sample_weight_mode".
[2021-11-24 19:25:06,747: INFO: 01_base_model_creation]: 
********************
[2021-11-24 19:25:06,747: INFO: 01_base_model_creation]: >>>>> stage creating base model started <<<<<
[2021-11-24 19:25:06,748: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2021-11-24 19:25:07,709: INFO: 01_base_model_creation]: >>>>> stage creating base model completed!<<<<<

